name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      GATSBY_API_BASE_URL: https://api.recosante.beta.gouv.fr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: deploy
